### ISSUE TITLE
Headphones error

### ISSUE THREAD

**Issue by gohryt** [KD-AIP/Hackintosh-E6440#1]
I'm new in Hackintosh usage and don't know what logs I may found and show, but it is a problem with AppleALC there. Built-in speakers works correctly, but when I'm using headphones it gives only noise.

I found this (1) solution but can't use it with ...

gohryt@Alexanders-MacBook-Pro Release % sudo cp -R hda-verb /usr/bin
Password:
cp: /usr/bin/hda-verb: Read-only file system

... error.

Is there any working solution for it?

1 - https://www.elitemacx86.com/threads/audio-distortion-when-using-headphones-on-laptops-clover-opencore.185/

Device is dell e6440 with 1366x768 display.

**Comment by KD-AIP** [comment]
You need to mount system as rw to editing the filesystem.Check out the method to mount system as rw:
![HERE](https://github.com/KD-AIP/Hackintosh-E6440/blob/Catalina_Stable/hackintool.png)

Sorry because i have too few time to working with the efi. So can you plz test your fixing solution and upload the result. Thanks 👍
